 

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SampleMatchRouteImport } from './routes/sample/match'
import { Route as ApiSampleMatchRouteImport } from './routes/api/sample/match'
import { Route as ApiSampleItemsRouteImport } from './routes/api/sample/items'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SampleMatchRoute = SampleMatchRouteImport.update({
  id: '/sample/match',
  path: '/sample/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSampleMatchRoute = ApiSampleMatchRouteImport.update({
  id: '/api/sample/match',
  path: '/api/sample/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSampleItemsRoute = ApiSampleItemsRouteImport.update({
  id: '/api/sample/items',
  path: '/api/sample/items',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sample/match': typeof SampleMatchRoute
  '/api/sample/items': typeof ApiSampleItemsRoute
  '/api/sample/match': typeof ApiSampleMatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sample/match': typeof SampleMatchRoute
  '/api/sample/items': typeof ApiSampleItemsRoute
  '/api/sample/match': typeof ApiSampleMatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sample/match': typeof SampleMatchRoute
  '/api/sample/items': typeof ApiSampleItemsRoute
  '/api/sample/match': typeof ApiSampleMatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sample/match' | '/api/sample/items' | '/api/sample/match'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sample/match' | '/api/sample/items' | '/api/sample/match'
  id:
    | '__root__'
    | '/'
    | '/sample/match'
    | '/api/sample/items'
    | '/api/sample/match'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SampleMatchRoute: typeof SampleMatchRoute
  ApiSampleItemsRoute: typeof ApiSampleItemsRoute
  ApiSampleMatchRoute: typeof ApiSampleMatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sample/match': {
      id: '/sample/match'
      path: '/sample/match'
      fullPath: '/sample/match'
      preLoaderRoute: typeof SampleMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sample/match': {
      id: '/api/sample/match'
      path: '/api/sample/match'
      fullPath: '/api/sample/match'
      preLoaderRoute: typeof ApiSampleMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sample/items': {
      id: '/api/sample/items'
      path: '/api/sample/items'
      fullPath: '/api/sample/items'
      preLoaderRoute: typeof ApiSampleItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SampleMatchRoute: SampleMatchRoute,
  ApiSampleItemsRoute: ApiSampleItemsRoute,
  ApiSampleMatchRoute: ApiSampleMatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
