/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimesIndexRouteImport } from './routes/times/index'
import { Route as ApiLinkPreviewRouteImport } from './routes/api/link-preview'
import { Route as ApiArchiveItemsRouteImport } from './routes/api/archive/items'
import { Route as ApiArchiveDatesRouteImport } from './routes/api/archive/dates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimesIndexRoute = TimesIndexRouteImport.update({
  id: '/times/',
  path: '/times/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkPreviewRoute = ApiLinkPreviewRouteImport.update({
  id: '/api/link-preview',
  path: '/api/link-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveItemsRoute = ApiArchiveItemsRouteImport.update({
  id: '/api/archive/items',
  path: '/api/archive/items',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArchiveDatesRoute = ApiArchiveDatesRouteImport.update({
  id: '/api/archive/dates',
  path: '/api/archive/dates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/times/': typeof TimesIndexRoute
  '/api/archive/dates': typeof ApiArchiveDatesRoute
  '/api/archive/items': typeof ApiArchiveItemsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/times': typeof TimesIndexRoute
  '/api/archive/dates': typeof ApiArchiveDatesRoute
  '/api/archive/items': typeof ApiArchiveItemsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/link-preview': typeof ApiLinkPreviewRoute
  '/times/': typeof TimesIndexRoute
  '/api/archive/dates': typeof ApiArchiveDatesRoute
  '/api/archive/items': typeof ApiArchiveItemsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/link-preview'
    | '/times/'
    | '/api/archive/dates'
    | '/api/archive/items'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/link-preview'
    | '/times'
    | '/api/archive/dates'
    | '/api/archive/items'
  id:
    | '__root__'
    | '/'
    | '/api/link-preview'
    | '/times/'
    | '/api/archive/dates'
    | '/api/archive/items'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLinkPreviewRoute: typeof ApiLinkPreviewRoute
  TimesIndexRoute: typeof TimesIndexRoute
  ApiArchiveDatesRoute: typeof ApiArchiveDatesRoute
  ApiArchiveItemsRoute: typeof ApiArchiveItemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/times/': {
      id: '/times/'
      path: '/times'
      fullPath: '/times/'
      preLoaderRoute: typeof TimesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/link-preview': {
      id: '/api/link-preview'
      path: '/api/link-preview'
      fullPath: '/api/link-preview'
      preLoaderRoute: typeof ApiLinkPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive/items': {
      id: '/api/archive/items'
      path: '/api/archive/items'
      fullPath: '/api/archive/items'
      preLoaderRoute: typeof ApiArchiveItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/archive/dates': {
      id: '/api/archive/dates'
      path: '/api/archive/dates'
      fullPath: '/api/archive/dates'
      preLoaderRoute: typeof ApiArchiveDatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLinkPreviewRoute: ApiLinkPreviewRoute,
  TimesIndexRoute: TimesIndexRoute,
  ApiArchiveDatesRoute: ApiArchiveDatesRoute,
  ApiArchiveItemsRoute: ApiArchiveItemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
